name: PHPUnit

on:
  push:
    branches: [main, 'tests-*']
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_sqlite
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --testdox
      - name: Upload PHPUnit result cache
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: phpunit-result
          path: .phpunit.result.cache
